language: go
matrix:
  include:
    - go: 1.7.5
    - go: 1.8
    - go: tip
  allow_failures:
    - go: tip
dist: trusty
sudo: true
before_install:
  - sudo apt-get -qq update
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo add-apt-repository ppa:saltstack/salt -y
  - sudo apt-get -qq update
  - sudo apt-get install glide -y
  - sudo apt-get install libzmq libzmq-dev libczmq-dev libsodium-dev
install:
  - glide install
  - go get github.com/mjibson/esc
  - go get github.com/ahmetb/govvv
  - go get github.com/franciscocpg/gox
  - go get github.com/tcnksm/ghr
  - go get github.com/sanbornm/go-selfupdate
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v $(glide novendor)
