language: go
matrix:
  include:
    - go: 1.7.x
    - go: 1.8.x
    - go: tip
  allow_failures:
    - go: tip
dist: trusty
sudo: true
before_install:
  - sudo apt-get -qq update
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo add-apt-repository ppa:saltstack/salt -y
  - sudo apt-get -qq update
  - sudo apt-get install glide -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get install -q -y cmake-data cmake
  - sudo apt-get install -q -y g++-5
  - export CXX="g++-5"
  - cd /tmp
  - wget https://github.com/zeromq/libzmq/releases/download/v4.2.2/zeromq-4.2.2.tar.gz
  - tar xvf zeromq-4.2.2.tar.gz
  - cd zeromq-4.2.2
  - sudo ./configure
  - sudo make -j7
  - sudo make install
install:
  - glide install --force
  - go get github.com/mjibson/esc
  - go get github.com/ahmetb/govvv
  - go get github.com/franciscocpg/gox
  - go get github.com/tcnksm/ghr
  - go get github.com/sanbornm/go-selfupdate
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v $(glide novendor)
